/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;
import java.io.PrintWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Donation extends javax.swing.JFrame {
    private final Home HomeFrameReference;
    private int points;
    private String username;
    /**
     * Creates new form Donation
     */
    public Donation(Home HomeFrame,int points,String username) {
        this.HomeFrameReference=HomeFrame;
        this.points=points;
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fAmount = new javax.swing.JTextField();
        donateBtn = new javax.swing.JButton();
        fNGO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("DONATION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Enter donation amount :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Enter NGO :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        fAmount.setBackground(new java.awt.Color(153, 204, 255));
        fAmount.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        getContentPane().add(fAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 280, 56));

        donateBtn.setBackground(new java.awt.Color(153, 204, 255));
        donateBtn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        donateBtn.setForeground(new java.awt.Color(255, 255, 255));
        donateBtn.setText(" Donate !");
        donateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(donateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        fNGO.setBackground(new java.awt.Color(153, 204, 255));
        fNGO.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        getContentPane().add(fNGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 280, 56));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\donate bg.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        this.HomeFrameReference.setVisible(true);
        HomeFrameReference.pack();
        HomeFrameReference.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_backBtnActionPerformed

    private void donateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtnActionPerformed
        double amount,donationAmount;
        int pointsEarned;
        String SUrl,SUser,SPass,query,NGO;
        SUrl="jdbc:mysql://localhost:3306/user";
        SUser="root";
        SPass="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st=con.createStatement();
            if("".equals(fAmount.getText())&&"".equals(fNGO.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter amount and NGO.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else if("".equals(fAmount.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter amount.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else if("".equals(fNGO.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter NGO.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else{
                amount=Double.parseDouble(fAmount.getText());
                NGO=fNGO.getText();
                donationAmount=amount*0.9;
                pointsEarned=(int)(amount*10);
                points+=pointsEarned;
                query = "UPDATE user SET points = " + points + " WHERE username = '" + username + "'";
                st.executeUpdate(query);
                HomeFrameReference.updatePoints(points);
                showMessageDialog(null,"Thank you for your donation! You've earned "+pointsEarned+" points.");
                try{
                    PrintWriter out=new PrintWriter(new FileOutputStream("Donation.txt",true));
                    out.println(username+" has donated "+donationAmount+" to "+NGO);
                    out.close();
                }
                catch(IOException e){
                    System.out.println(e.getMessage());
                }
                fAmount.setText("");
                fNGO.setText("");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_donateBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton donateBtn;
    private javax.swing.JTextField fAmount;
    private javax.swing.JTextField fNGO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
