/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author ACER
 */
public class Home extends javax.swing.JFrame {
    private String username;
    private String email;
    
    private String regDate;
    private int points;
    /**
     * Creates new form Menu
     */
    public Home(String username,int points,String email,String regDate) {
        initComponents();
        this.username=username;
        this.points=points;
        this.email=email;
        
        this.regDate=regDate;
        fUsername.setText(username);
        fPoints.setText(Integer.toString(points));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileBtn = new javax.swing.JButton();
        checkInBtn = new javax.swing.JButton();
        News = new javax.swing.JButton();
        donationBtn = new javax.swing.JButton();
        triviaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fPoints = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        pointShopBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileBtn.setBackground(new java.awt.Color(0, 102, 102));
        profileBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileBtn.setText("profile");
        profileBtn.setMaximumSize(new java.awt.Dimension(150, 37));
        profileBtn.setMinimumSize(new java.awt.Dimension(150, 37));
        profileBtn.setPreferredSize(new java.awt.Dimension(150, 37));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 209, 55));

        checkInBtn.setBackground(new java.awt.Color(0, 102, 102));
        checkInBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        checkInBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkInBtn.setText("chekc-in");
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 435, 209, 55));

        News.setBackground(new java.awt.Color(0, 102, 102));
        News.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        News.setForeground(new java.awt.Color(255, 255, 255));
        News.setText("news section");
        News.setMaximumSize(new java.awt.Dimension(150, 37));
        News.setMinimumSize(new java.awt.Dimension(150, 37));
        News.setPreferredSize(new java.awt.Dimension(150, 37));
        News.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewsActionPerformed(evt);
            }
        });
        getContentPane().add(News, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 230, 55));

        donationBtn.setBackground(new java.awt.Color(0, 102, 102));
        donationBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        donationBtn.setForeground(new java.awt.Color(255, 255, 255));
        donationBtn.setText("donation");
        donationBtn.setMaximumSize(new java.awt.Dimension(150, 37));
        donationBtn.setMinimumSize(new java.awt.Dimension(150, 37));
        donationBtn.setPreferredSize(new java.awt.Dimension(150, 37));
        donationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(donationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 435, 209, 55));

        triviaBtn.setBackground(new java.awt.Color(0, 102, 102));
        triviaBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        triviaBtn.setForeground(new java.awt.Color(255, 255, 255));
        triviaBtn.setText("daily trivia");
        triviaBtn.setMaximumSize(new java.awt.Dimension(150, 37));
        triviaBtn.setMinimumSize(new java.awt.Dimension(150, 37));
        triviaBtn.setPreferredSize(new java.awt.Dimension(150, 37));
        triviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triviaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(triviaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 230, 209, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Welcome! ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 34, -1, -1));

        fUsername.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        fUsername.setForeground(new java.awt.Color(0, 102, 102));
        fUsername.setText("username");
        getContentPane().add(fUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Current Points: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 34, -1, -1));

        fPoints.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        fPoints.setForeground(new java.awt.Color(0, 102, 102));
        fPoints.setText("8");
        getContentPane().add(fPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 34, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(0, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("logout");
        logoutBtn.setMaximumSize(new java.awt.Dimension(150, 37));
        logoutBtn.setMinimumSize(new java.awt.Dimension(150, 37));
        logoutBtn.setPreferredSize(new java.awt.Dimension(150, 37));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 622, 209, 55));

        pointShopBtn.setBackground(new java.awt.Color(0, 102, 102));
        pointShopBtn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        pointShopBtn.setForeground(new java.awt.Color(255, 255, 255));
        pointShopBtn.setText("points shop");
        pointShopBtn.setMaximumSize(new java.awt.Dimension(150, 37));
        pointShopBtn.setMinimumSize(new java.awt.Dimension(150, 37));
        pointShopBtn.setPreferredSize(new java.awt.Dimension(150, 37));
        pointShopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointShopBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pointShopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 435, 209, 55));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\menu bg.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        Profile ProfileFrame=new Profile(this,username,email,regDate);
        ProfileFrame.setVisible(true);
        ProfileFrame.pack();
        ProfileFrame.setLocationRelativeTo(null);
        this.dispose();               
    }//GEN-LAST:event_profileBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        String SUrl,SUser,SPass,query,lastCheckInDate;
        boolean found=false;
        SUrl="jdbc:mysql://localhost:3306/user";
        SUser="root";
        SPass="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st=con.createStatement();
            query="SELECT * FROM checkin WHERE username='"+username+"'"; 
            ResultSet rs=st.executeQuery(query);
            LocalDate today=LocalDate.now();
            while(rs.next()){
                lastCheckInDate=rs.getString("date");
                LocalDate lastCheckIn = LocalDate.parse(lastCheckInDate);

                if(lastCheckIn.equals(today)){
                    showMessageDialog(null,"You've already checked in today.");
                    found=true;
                    break;
                }
            }
            if(!found){
                query="INSERT INTO checkin(username,date)"+"VALUES('"+username+"','"+today+"')";
                st.executeUpdate(query);
                points++;
                query = "UPDATE user SET points = " + points + " WHERE username = '" + username + "'";
                st.executeUpdate(query);
                fPoints.setText(Integer.toString(points));
                showMessageDialog(null,"Checked in successfully");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_checkInBtnActionPerformed
   
    
    private void NewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewsActionPerformed
        NewsSection NewsSectionFrame = new NewsSection(this);
        NewsSectionFrame.setVisible(true);
        NewsSectionFrame.pack ();
        NewsSectionFrame.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_NewsActionPerformed

    private void donationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationBtnActionPerformed
        Donation DonationFrame=new Donation(this,points,username);
        DonationFrame.setVisible(true);
        DonationFrame.pack();
        DonationFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_donationBtnActionPerformed

    private void triviaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triviaBtnActionPerformed
        Trivia TriviaFrame=new Trivia(this,points,username,regDate);
        TriviaFrame.setVisible(true);
        TriviaFrame.pack();
        TriviaFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_triviaBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
        Login LoginFrame=new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void pointShopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointShopBtnActionPerformed
        PointShop PointShopFrame=new PointShop(this,username);
        PointShopFrame.setVisible(true);
        PointShopFrame.pack();
        PointShopFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_pointShopBtnActionPerformed

    public void updatePoints(int points){
        fPoints.setText(Integer.toString(points));
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton News;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JButton donationBtn;
    private javax.swing.JLabel fPoints;
    private javax.swing.JLabel fUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton pointShopBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton triviaBtn;
    // End of variables declaration//GEN-END:variables
}
