/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ACER
 */
public class Merchandise extends javax.swing.JFrame {
    private final PointShop PointShopFrameReference;
    //private int points;
    private String username;
    /**
     * Creates new form Merchandise
     */
    public Merchandise(PointShop PointShopFrame,String username) {
        this.PointShopFrameReference=PointShopFrame;
        //this.points=points;
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fID = new javax.swing.JTextField();
        fAddress = new javax.swing.JTextField();
        fQuantity = new javax.swing.JTextField();
        checkOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 750));
        getContentPane().setLayout(null);

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(0, 0, 100, 100);

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Merchandise");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 70, 460, 75);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Merchandise ID: merch-1 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 420, 42);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Merchandise ID: merch-2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 170, 420, 42);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Merchandise ID: merch-3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 310, 430, 42);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Required points: 500");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 230, 380, 42);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Required points: 1000");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 230, 390, 42);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Required points: 500");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 370, 350, 42);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Merchandise ID: merch-4");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 310, 440, 42);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Required points: 1000");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(530, 370, 390, 42);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Enter the merchandise ID: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(54, 504, 440, 42);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Enter the quantity:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(54, 571, 330, 42);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Enter your address: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(54, 638, 340, 42);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Order Details");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(54, 440, 260, 46);

        fID.setBackground(new java.awt.Color(204, 255, 204));
        fID.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fID.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(fID);
        fID.setBounds(490, 510, 350, 42);

        fAddress.setBackground(new java.awt.Color(204, 255, 204));
        fAddress.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fAddress.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(fAddress);
        fAddress.setBounds(490, 650, 350, 42);

        fQuantity.setBackground(new java.awt.Color(204, 255, 204));
        fQuantity.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fQuantity.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(fQuantity);
        fQuantity.setBounds(490, 580, 350, 42);

        checkOutBtn.setBackground(new java.awt.Color(204, 255, 204));
        checkOutBtn.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(0, 51, 51));
        checkOutBtn.setText("Check Out");
        checkOutBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkOutBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkOutBtn);
        checkOutBtn.setBounds(850, 650, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\shop bg.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        this.PointShopFrameReference.setVisible(true);
        PointShopFrameReference.pack();
        PointShopFrameReference.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        String ID,address;
        int quantity,pointsRequired=0,points=0;
        String SUrl,SUser,SPass,query;
        boolean found=true;
        SUrl="jdbc:mysql://localhost:3306/user";
        SUser="root";
        SPass="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st=con.createStatement();
            if("".equals(fID.getText())&&"".equals(fID.getText())&&"".equals(fAddress.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter merchandise ID, quantity and address.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else if("".equals(fID.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter merchandise ID.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else if("".equals(fQuantity.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter quantity.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else if("".equals(fAddress.getText())){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter address.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else{
                ID=fID.getText();
                quantity=Integer.parseInt(fQuantity.getText());
                address=fAddress.getText();
                query="SELECT * FROM user WHERE username='"+username+"'"; 
                ResultSet rs=st.executeQuery(query);
                while(rs.next()){
                    points=rs.getInt("points");
                }
                if(ID.equals("merch-1")||ID.equals("merch-3")){
                    pointsRequired=(quantity*500);
                }
                else if(ID.equals("merch-2")||ID.equals("merch-4")){
                    pointsRequired=(quantity*1000);
                }
                else {
                    found=false;
                    JOptionPane.showMessageDialog(new JFrame(),"Merchandise not found","Error",JOptionPane.ERROR_MESSAGE); 
                }
                if(found){
                    if(points>=pointsRequired){
                        points-=pointsRequired;
                        query = "UPDATE user SET points = " + points + " WHERE username = '" + username + "'";
                        st.executeUpdate(query);
                        PointShopFrameReference.updatePoints(points);
                        showMessageDialog(null,"Check-out successfully.");
                        try{
                            PrintWriter out=new PrintWriter(new FileOutputStream("MerchandiseOrder.txt",true));
                            out.println(username+" orders "+quantity+" "+ID+" to "+address);
                            out.close();
                        }
                        catch(IOException e){
                            System.out.println(e.getMessage());
                        }
                    }
                    else{ 
                        JOptionPane.showMessageDialog(new JFrame(),"Not enough points","Error",JOptionPane.ERROR_MESSAGE); 
                    }
                }
                fID.setText("");
                fQuantity.setText("");
                fAddress.setText("");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_checkOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JTextField fAddress;
    private javax.swing.JTextField fID;
    private javax.swing.JTextField fQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
