/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ACER
 */
public class PlantTree extends javax.swing.JFrame {
    private final PointShop PointShopFrameReference;
    //private int points;
    private String username;
    /**
     * Creates new form PlantTree
     */
    public PlantTree(PointShop PointShopFrame,String username) {
        this.PointShopFrameReference=PointShopFrame;
        //this.points=points;
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        checkOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Plant tree");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Enter the name to be written on the planted tree:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Required points to plant a tree: 1000");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Order Details");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        fName.setBackground(new java.awt.Color(204, 255, 204));
        fName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fName.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 650, 50));

        checkOutBtn.setBackground(new java.awt.Color(204, 255, 204));
        checkOutBtn.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(0, 51, 51));
        checkOutBtn.setText("Check-out");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\tree bg.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        this.PointShopFrameReference.setVisible(true);
        PointShopFrameReference.pack();
        PointShopFrameReference.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        String name;
        String SUrl,SUser,SPass,query;
        int points=0;
        SUrl="jdbc:mysql://localhost:3306/user";
        SUser="root";
        SPass="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st=con.createStatement();
            name=fName.getText();
            query="SELECT * FROM user WHERE username='"+username+"'"; 
            ResultSet rs=st.executeQuery(query);
                while(rs.next()){
                    points=rs.getInt("points");
                }
            if(name.equals("")){
                JOptionPane.showMessageDialog(new JFrame(),"Please enter amount.","Error",JOptionPane.ERROR_MESSAGE); 
            }
            else{
                if(points>=1000){
                    points-=1000;
                    query = "UPDATE user SET points = " + points + " WHERE username = '" + username + "'";
                    st.executeUpdate(query);
                    PointShopFrameReference.updatePoints(points);
                    showMessageDialog(null,"Check-out successfully.");
                    try{
                        PrintWriter out=new PrintWriter(new FileOutputStream("TreePlantOrder.txt",true));
                        out.println(username+" plants a tree with the name \" "+name+" \"");
                        out.close();
                    }
                    catch(IOException e){
                        System.out.println(e.getMessage());
                    }
                }
                else{ 
                    JOptionPane.showMessageDialog(new JFrame(),"Not enough points","Error",JOptionPane.ERROR_MESSAGE); 
                }
                fName.setText("");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }      
    }//GEN-LAST:event_checkOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
