/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;
import java.text.ParseException;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JTextArea;
import java.io.IOException;

public class DisplayNews extends javax.swing.JFrame {
     private List<NewsFilter.NewsArticle> fileNewsList ;
     private final NewsSection NewsFrame ;
    
    public DisplayNews(List<NewsFilter.NewsArticle> fileNewsList, NewsSection NewsFrame) {
        this.fileNewsList = fileNewsList;
        this.NewsFrame = NewsFrame;
        initComponents();
        displayNews();
    }
    
    private void displayNews(){
        StringBuilder fileNewsText = new StringBuilder();
        
        
         if (fileNewsList != null && !fileNewsList.isEmpty()) {
         int count = Math.min(fileNewsList.size(), 5);
            for (int i = 0; i < count; i++) {
                NewsFilter.NewsArticle news = fileNewsList.get(i);
                fileNewsText.append(news.title).append("\n").append(news.url).append("\n")
                        .append(new SimpleDateFormat("dd MMM yyyy", Locale.ENGLISH).format(news.date)).append("\n\n");
            }
            setJTextAreaText(fileNewsText.toString(),jTextArea1);
        } else {
            System.out.println("NewsList is null. Cannot display news.");
        }
    
    }
     private void setJTextAreaText(String text, javax.swing.JTextArea targetTextArea){
         targetTextArea.setText(text);
     }
     
                                      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        RealNews = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOP 5 NEWS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 410, 100));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 600, 410));

        RealNews.setBackground(new java.awt.Color(255, 255, 204));
        RealNews.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        RealNews.setForeground(new java.awt.Color(0, 0, 0));
        RealNews.setText("MORE");
        RealNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealNewsActionPerformed(evt);
            }
        });
        getContentPane().add(RealNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, 140, 60));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        Back.setText("jButton1");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\news2.0.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 986, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealNewsActionPerformed
         try {
        Api api = new Api();  // Create an instance of the Api class
        List<NewsFilter.NewsArticle> apiNewsList = api.getNewsNature();  // Call the getNewsNature method

        // Now, you can pass apiNewsList to the Real frame
        Real jframe = new Real(apiNewsList);
        jframe.setVisible(true);
        jframe.pack();
        jframe.setLocationRelativeTo(null);
    } catch (IOException e) {
        e.printStackTrace();
        // Handle the IOException as needed
    }
    }//GEN-LAST:event_RealNewsActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.NewsFrame.setVisible(true);
        NewsFrame.pack();
        NewsFrame.setLocationRelativeTo(null);
        this.dispose();    
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton RealNews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
