/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

/**
 *
 * @author ACER
 */
public class PointShop extends javax.swing.JFrame {
    private final Home HomeFrameReference;
    //private int points;
    private String username;
    /**
     * Creates new form PointShop
     */
    public PointShop(Home HomeFrame,String username) {
        this.HomeFrameReference=HomeFrame;
        //this.points=points;
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        merchandiseBtn = new javax.swing.JButton();
        treeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("POINTS SHOP");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        merchandiseBtn.setBackground(new java.awt.Color(255, 153, 153));
        merchandiseBtn.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        merchandiseBtn.setForeground(new java.awt.Color(255, 255, 255));
        merchandiseBtn.setText("Buy nature-caring merchandise");
        merchandiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merchandiseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(merchandiseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        treeBtn.setBackground(new java.awt.Color(255, 153, 153));
        treeBtn.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        treeBtn.setForeground(new java.awt.Color(255, 255, 255));
        treeBtn.setText("Plant a tree");
        treeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(treeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\shop bg.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.HomeFrameReference.setVisible(true);
        HomeFrameReference.pack();
        HomeFrameReference.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void merchandiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merchandiseBtnActionPerformed
        Merchandise MerchandiseFrame=new Merchandise(this,username);
        MerchandiseFrame.setVisible(true);
        MerchandiseFrame.pack();
        MerchandiseFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_merchandiseBtnActionPerformed

    private void treeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeBtnActionPerformed
        PlantTree PlantTreeFrame=new PlantTree(this,username);
        PlantTreeFrame.setVisible(true);
        PlantTreeFrame.pack();
        PlantTreeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_treeBtnActionPerformed

    public void updatePoints(int points){
        HomeFrameReference.updatePoints(points);;
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton merchandiseBtn;
    private javax.swing.JButton treeBtn;
    // End of variables declaration//GEN-END:variables
}
