/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

/**
 *
 * @author ACER
 */
public class Profile extends javax.swing.JFrame {
    private final Home HomeFrameReference;
    private String  username;
    private String  email;
    
    private String  regDate;
    private int points;


    /**
     * Creates new form Profile
     */
    public Profile(Home HomeFrame,String username,String email,String regDate) {
        initComponents();
        this.HomeFrameReference=HomeFrame;
        this.username=username;
        this.points=points;
        this.email=email;
        
        this.regDate=regDate;
        fUsername.setText(username);
        fEmail.setText(email);
        
        fRegDate.setText(regDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fPassword = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fRegDate = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Username: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        fUsername.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        fUsername.setForeground(new java.awt.Color(0, 102, 102));
        fUsername.setText("name");
        getContentPane().add(fUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        fEmail.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        fEmail.setForeground(new java.awt.Color(0, 102, 102));
        fEmail.setText("email");
        getContentPane().add(fEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        fPassword.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        fPassword.setForeground(new java.awt.Color(0, 102, 102));
        fPassword.setText("password");
        getContentPane().add(fPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Registration Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        fRegDate.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        fRegDate.setForeground(new java.awt.Color(0, 102, 102));
        fRegDate.setText("date");
        getContentPane().add(fRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("PROFILE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\profile bg.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        this.HomeFrameReference.setVisible(true);
        HomeFrameReference.pack();
        HomeFrameReference.setLocationRelativeTo(null);
        this.dispose();    
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public void setUsername(String name){
        fUsername.setText(name);
    }
    public void setEmail(String email){
        fEmail.setText(email);
    }
    public void setPassword(String password){
        fPassword.setText(password);
    }
    public void setRegDate(String regDate){
        fRegDate.setText(regDate);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel fEmail;
    private javax.swing.JLabel fPassword;
    private javax.swing.JLabel fRegDate;
    private javax.swing.JLabel fUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
